"""Updated migrations.

Revision ID: ecbf06f6e268
Revises: 694ca9a086c7
Create Date: 2024-03-12 13:19:46.617721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecbf06f6e268'
down_revision = '694ca9a086c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fosters')
    op.drop_table('admins')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='admins_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='admins_pkey')
    )
    op.create_table('fosters',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cat_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cat_id'], ['cats.id'], name='fosters_cat_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fosters_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='fosters_pkey')
    )
    # ### end Alembic commands ###
